### PR TITLE
Misc warnings

### PR DESCRIPTION
**Pull request by seanm**

### CODE REVIEW

**Comment by seanm** [comment]
@sjarman28  care to review?

**Comment by sjarman28** [comment]
The LJUSB_libusbError() function should not be changed to use ssize_t. ssize_t is not always guaranteed to be able to hold negative values below -1 and the libusb errors that can be passed to the function are negative values that can exceed -1.

The check that "count > UINT16_MAX" is valid for our devices, however I am hesitant to allow the comparison. It seems UINT16_MAX may not be guaranteed to be defined, so it would be preferable to remove the stdint.h include and define UINT16_MAX as 65535 (if undefined). Bulk and interrupt transfers should not be artificially limited to 65535, it should only be limited by the size of an int (2^31 - 1 should be a fairly safe minimum for this library). Any passed value that may be beyond the actual maximum transfer size should be handled by libusb. It is important to note that these changes would only handle a specific edge case that is unlikely to happen in practice. Additionally, the issue would be better fixed by changing the type of the count parameter to int (perhaps int32_t) and splitting the control transfer from the other transfer types, which would require a major version update to the Exodriver. Because of this, I am not going to approve the change and leave it as something to do if we decide to commit to a major revision.

LJUSB_DoTransfer() should not be redefined to have a constant buffer, it is modified during read operations. Additionally, the cast from BYTE* to unsigned char* should be left as implicit as we do not want to risk reinterpreting the data.

**Comment by seanm** [comment]
Thanks for reviewing!

> The LJUSB_libusbError() function should not be changed to use ssize_t. ssize_t is not always guaranteed to be able to hold negative values below -1 and the libusb errors that can be passed to the function are negative values that can exceed -1.

Wow, the POSIX spec is really vague/generous about that. But really, I'm pretty sure every platform that libusb supports uses two's complement.  I'll see if I can address the warning in another way...

> The check that "count > UINT16_MAX" is valid for our devices, however I am hesitant to allow the comparison. It seems UINT16_MAX may not be guaranteed to be defined, so it would be preferable to remove the stdint.h include and define UINT16_MAX as 65535 (if undefined). Bulk and interrupt transfers should not be artificially limited to 65535, it should only be limited by the size of an int (2^31 - 1 should be a fairly safe minimum for this library). Any passed value that may be beyond the actual maximum transfer size should be handled by libusb. It is important to note that these changes would only handle a specific edge case that is unlikely to happen in practice. Additionally, the issue would be better fixed by changing the type of the count parameter to int (perhaps int32_t) and splitting the control transfer from the other transfer types, which would require a major version update to the Exodriver. Because of this, I am not going to approve the change and leave it as something to do if we decide to commit to a major revision.

Indeed I didn't want to change the public API, which is why I added the check against UINT16_MAX as better than nothing.  Without the check, calling `libusb_control_transfer` [here](https://github.com/labjack/exodriver/blob/eb541d2b5a2b0f6a1d45a6e4132c434841752de1/liblabjackusb/labjackusb.c#L716) passes an `int` to the second-to-last parameter (which is a `uint16_t`).  If the `int` is larger than 65535, that's undefined behaviour.  This was the compiler's warning.

I could just replace UINT16_MAX with the raw number 65535.

> LJUSB_DoTransfer() should not be redefined to have a constant buffer, it is modified during read operations.

Ah. OK, will take another look at this part.

>Additionally, the cast from BYTE* to unsigned char* should be left as implicit as we do not want to risk reinterpreting the data.

There's no difference: `typedef unsigned char BYTE;` so no reinterpretation.

**Comment by seanm** [comment]
OK, I removed the const changes, I don't see any way to remove the `-Wcast-qual` warnings without changing public API.

I changed `UINT16_MAX` to 65535, and removed the include of `stdint.h`.

For the `ssize_t` thing, I don't see a better way.  Perhaps you have an idea?  The warnings I'm trying to silence are the various places (ex `LJUSB_OpenDevice`) that pass an `ssize_t` to `LJUSB_libusbError`, giving `Implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int'`.  I really doubt any platform that libusb supports has a `ssize_t` that can't represent everything `int` can.

**Comment by sjarman28** [comment]
The UINT16_MAX/65535 transfer size check seems okay to add in.

I think we can pretty safely cast the `ssize_t` variable to int for the `LJUSB_libusbError` function. The only time we pass an `ssize_t` to `LJUSB_libusbError` is when the value is <0 (a libusb error). Using an `int` seems the most appropriate since libusb normally uses `int` for their error return.

**Comment by seanm** [comment]
OK, I pushed updates, but don't see them here for some reason... perhaps because you closed this PR.  Could you try setting it back to open?

**Comment by sjarman28** [comment]
Apologies. Due to the changes to your branch I am unable to reopen and merge in changes from this pull request. Please submit a new pull request.

**Pull request closed without merging**
