### PR TITLE
More review

### PR DESCRIPTION
**Pull request by seanm**

### CODE REVIEW

**Comment by seanm** [comment]
@sjarman28 @davelopez01 care to review?

**Comment by seanm** [comment]
@sjarman28 I've rebased this to latest master, i.e. to include https://github.com/labjack/exodriver/pull/36

**Review by sjarman28 — APPROVED** [review]
Looks good, thanks for the contribution.

**Comment by seanm** [comment]
Thanks for your review.  I have another patch to share, but have been waiting for this one to land so I can I can rebase...

**Pull request merged**
